"""
grpo_optimization.py

This script does:
1. Group Advantage Computation (Standardizing rewards across G trajectories).
2. The Masking Indicator M_{i,t} (Ensuring environment snippets are not optimized).
3. The GRPO Loss Function (Policy Gradient + KL Divergence + Entropy Loss).
"""

import torch
import torch.nn.functional as F
from typing import Tuple

# ==============================================================================
# PART A: GROUP ADVANTAGE COMPUTATION 
# ==============================================================================

def compute_group_advantages(rewards: torch.Tensor, epsilon_0: float = 1e-8) -> torch.Tensor:
    """
    Computes advantage A_i by standardizing the rewards within the group of G trajectories.
    Formula: A_i = (r_i - mean) / (std + epsilon_0)
    
    Args:
        rewards: Tensor of shape (G,) representing the outcome reward of each trajectory.
        epsilon_0: Small constant for numerical stability.
    Returns:
        advantages: Tensor of shape (G,)
    """
    mean_reward = rewards.mean()
    std_reward = rewards.std(unbiased=False) # standard deviation of the group
    
    # If all rewards in the group are identical, advantages are 0 to prevent unstable gradients
    if std_reward < 1e-6:
        return torch.zeros_like(rewards)
        
    advantages = (rewards - mean_reward) / (std_reward + epsilon_0)
    return advantages


# ==============================================================================
# PART B: THE MASKING INDICATOR M_{i,t} 
# ==============================================================================

def create_trajectory_mask(
    input_ids: torch.Tensor, 
    prompt_length: int, 
    tokenizer, 
    info_start_tag="<information>", 
    info_end_tag="</information>"
) -> torch.Tensor:
    """
    Creates the Masking Indicator M_{i,t} in {0, 1}.
    M_{i,t} = 1 if token t was generated by the LLM.
    M_{i,t} = 0 if token t belongs to the prompt OR was returned by Environment E (inside <information> tags).
    
    Args:
        input_ids: Tensor of shape (G, T)
        prompt_length: Integer length of the 1-shot cold start prompt.
        tokenizer: HuggingFace tokenizer.
    Returns:
        mask: FloatTensor of shape (G, T) containing 1.0 or 0.0
    """
    G, T = input_ids.shape
    mask = torch.ones((G, T), dtype=torch.float32, device=input_ids.device)
    
    # 1. Mask out the prompt
    mask[:, :prompt_length] = 0.0
    
    # 2. Mask out the environment-returned text (snippets inside <information> tags)
    for i in range(G):
        # Decode the tokens to find the character/token boundaries of the tags
        tokens = input_ids[i].tolist()
        in_environment_snippet = False
        
        for t in range(prompt_length, T):
            # We check the decoded string representation of the current context.
            # (In a highly optimized production setting, you'd match exact token IDs of the tags)
            token_str = tokenizer.decode([tokens[t]], skip_special_tokens=True)
            
            if info_start_tag in token_str or (t > 0 and info_start_tag in tokenizer.decode(tokens[t-2:t+1])):
                in_environment_snippet = True
                
            if in_environment_snippet:
                mask[i, t] = 0.0 # M_{i,t} = 0 (Environment token)
                
            if info_end_tag in token_str or (t > 0 and info_end_tag in tokenizer.decode(tokens[t-2:t+1])):
                in_environment_snippet = False
                mask[i, t] = 0.0 # Ensure the closing tag is also masked
                
    return mask


# ==============================================================================
# PART C: GRPO LOSS FUNCTION 
# ==============================================================================

class GRPOLoss(torch.nn.Module):
    """
    Calculates the complete L_GRPO(\theta) objective.
    L_GRPO = L_PG + \beta * L_KL - \alpha * L_Entropy
    """
    def __init__(self, clip_epsilon: float = 0.2, beta: float = 0.01, alpha: float = 0.05):
        super().__init__()
        self.clip_eps = clip_epsilon # \varepsilon
        self.beta = beta             # KL Divergence penalty coefficient
        self.alpha = alpha           # Entropy bonus coefficient

    def forward(
        self, 
        logits_theta: torch.Tensor,     # \pi_\theta (current policy being optimized)[G, T, V]
        logits_old: torch.Tensor,       # \pi_{\theta_old} (policy that generated trajectories) [G, T, V]
        logits_ref: torch.Tensor,       # \pi_{\theta_ref} (frozen reference policy) [G, T, V]
        actions: torch.Tensor,          # The actual token IDs generated [G, T]
        advantages: torch.Tensor,       # A_i computed for the group [G]
        mask: torch.Tensor              # M_{i,t}[G, T]
    ) -> Tuple[torch.Tensor, dict]:
        
        G, T, V = logits_theta.shape
        
        # Shift actions to align with logit predictions (next token prediction)
        # Logits at t predict action at t+1. 
        # For simplicity in this functional math mapping, we assume aligned shapes via slicing beforehand.
        
        # 1. Compute probabilities for the taken actions
        # log_prob = log(softmax(logits))
        log_pi_theta = F.log_softmax(logits_theta, dim=-1).gather(dim=-1, index=actions.unsqueeze(-1)).squeeze(-1)
        log_pi_old = F.log_softmax(logits_old, dim=-1).gather(dim=-1, index=actions.unsqueeze(-1)).squeeze(-1)
        log_pi_ref = F.log_softmax(logits_ref, dim=-1).gather(dim=-1, index=actions.unsqueeze(-1)).squeeze(-1)

        # 2. Policy Gradient Loss (L_PG)
        # \rho_{i,t}(\theta) = \pi_\theta / \pi_old = exp(log \pi_\theta - log \pi_old)
        ratio = torch.exp(log_pi_theta - log_pi_old)
        
        # Broadcast advantages to [G, T]
        adv_expanded = advantages.unsqueeze(-1).expand(-1, T)
        
        surr1 = ratio * adv_expanded
        surr2 = torch.clamp(ratio, 1.0 - self.clip_eps, 1.0 + self.clip_eps) * adv_expanded
        
        # Apply mask and mean over valid tokens
        pg_loss_per_token = torch.min(surr1, surr2) * mask
        L_PG = - (pg_loss_per_token.sum() / mask.sum()) # Negative because we MINIMIZE loss in PyTorch
        
        # 3. KL Divergence Loss (L_KL) - Unbiased per-token estimator
        # ratio_kl = \pi_ref / \pi_\theta
        ratio_kl = torch.exp(log_pi_ref - log_pi_theta)
        # formula: (\pi_ref / \pi_\theta) - log(\pi_ref / \pi_\theta) - 1
        kl_per_token = (ratio_kl - torch.log(ratio_kl) - 1.0) * mask
        L_KL = kl_per_token.sum() / mask.sum()
        
        # 4. Entropy Loss (L_Entropy)
        # parameterization: log(\sum e^X) - \sum p * X
        # Mathematically equivalent to standard Categorical entropy: - \sum p * log(p)
        pi_theta_probs = F.softmax(logits_theta, dim=-1)
        # Entropy = - \sum (P * log P)
        entropy_per_token = -torch.sum(pi_theta_probs * F.log_softmax(logits_theta, dim=-1), dim=-1) * mask
        # Note the denominator is exactly \sum_{i,t} M_{i,t} as per your formula
        L_Entropy = entropy_per_token.sum() / mask.sum()

        # 5. Total GRPO Loss
        total_loss = L_PG + (self.beta * L_KL) - (self.alpha * L_Entropy)

        # Return loss and metrics dictionary for tracking
        metrics = {
            "L_PG": L_PG.item(),
            "L_KL": L_KL.item(),
            "L_Entropy": L_Entropy.item(),
            "Total_Loss": total_loss.item()
        }
        
        return total_loss, metrics


# ==============================================================================
# PART D: EXECUTION / TESTING SCRIPT (Demonstrating the Mathematics)
# ==============================================================================
if __name__ == "__main__":
    print("-" * 60)
    print("GRPO LOSS FUNCTION & OPTIMIZATION MODULE")
    print("-" * 60)
    
    # 1. Simulate a Group Size (G) and Sequence Length (T), Vocab Size (V)
    G = 4   # Evaluate a group of trajectories
    T = 20  # Tokens per trajectory
    V = 100 # Mock vocabulary size
    
    print(f"Simulating Group Trajectories: G={G}, Sequence Length T={T}")
    
    # 2. Simulate Outcome Rewards R(x,y) from the Reward Model
    # E.g., Trajectory 0 and 1 got Exact Match (1.0), Trajectory 2 got Wrong (0.0), Traj 3 Format Err (-0.1)
    mock_rewards = torch.tensor([1.0, 1.0, 0.0, -0.1], dtype=torch.float32)
    
    # Calculate group advantages A_i
    advantages = compute_group_advantages(mock_rewards)
    print(f"Group Rewards:    {mock_rewards.tolist()}")
    print(f"Group Advantages: {advantages.tolist()}")
    
    # 3. Simulate Model Logits and Actions
    # Requires_grad=True simulates the Policy LLM we are optimizing
    logits_theta = torch.randn(G, T, V, requires_grad=True) 
    # Old policy and Reference policy are frozen (no grad)
    logits_old = logits_theta.detach().clone() + 0.05 * torch.randn(G, T, V) 
    logits_ref = logits_theta.detach().clone() + 0.1 * torch.randn(G, T, V)
    
    # Simulate generated token actions
    actions = torch.randint(0, V, (G, T))
    
    # 4. Simulate the Masking Indicator (M_{i,t})
    # For demonstration, assume prompt length is 5 tokens, and tokens 10-15 were environment search snippets
    mask = torch.ones((G, T), dtype=torch.float32)
    mask[:, :5] = 0.0      # Mask prompt
    mask[:, 10:15] = 0.0   # Mask <information> snippet
    
    print(f"Masking Indicator (Trajectory 0): {mask[0].tolist()}")
    
    # 5. Initialize and Compute GRPO Loss
    print("\nComputing GRPO Objective Function...")
    grpo_criterion = GRPOLoss(clip_epsilon=0.2, beta=0.01, alpha=0.05)
    
    loss, metrics = grpo_criterion(
        logits_theta=logits_theta,
        logits_old=logits_old,
        logits_ref=logits_ref,
        actions=actions,
        advantages=advantages,
        mask=mask
    )
    
    print("\nCalculated Loss Components:")
    for key, val in metrics.items():
        print(f"  - {key}: {val:.4f}")
        
    # 6. Verify Backpropagation works flawlessly
    print("\nExecuting backward pass (Policy Optimization)...")
    loss.backward()
    
    if logits_theta.grad is not None:
        print("Success! Gradients computed for Policy LLM (\pi_\theta).")
        print(f"Gradient norm: {logits_theta.grad.norm().item():.4f}")
    else:
        print("Error: Gradients failed to compute.")
    print("-" * 60)